# Generated by Django 4.2.4 on 2023-08-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
