# Generated by Django 4.2.4 on 2023-08-25 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recipes_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='name',
        ),
        migrations.AddField(
            model_name='recipes',
            name='title',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cover_image',
            field=models.ImageField(blank=True, default='', upload_to='recipes/covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
