# Generated by Django 4.2.4 on 2023-08-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_recipes_name_recipes_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='preparation_time_unit',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='servings_unit',
            field=models.TextField(max_length=65),
        ),
    ]
