# Generated by Django 4.2.4 on 2023-08-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recipes_preparation_time_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='servings_unit',
            field=models.CharField(max_length=65),
        ),
    ]
