# Generated by Django 4.2.4 on 2023-08-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_recipes_servings_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(max_length=65),
        ),
    ]
