# Generated by Django 4.2.4 on 2023-09-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_category_categoryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
