# Generated by Django 4.2.4 on 2023-09-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_remove_tag_content_type_remove_tag_object_id'),
        ('app', '0007_alter_recipes_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(to='tag.tag'),
        ),
    ]
