# Generated by Django 4.2.4 on 2023-10-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_recipes_options_alter_recipes_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='num_preparations',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='num_servings',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
